### ISSUE TITLE
Decide how to handle tx fees

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/statemint#21]
Two decisions to make about transaction fees:

1. How much to charge? I have configured the runtime to charge 1/10 the tx fees as the Relay Chain would charge. I think transactions on parachains should be cheaper as the execution does not affect other parachains. Note that I left the target block fullness at 25%, but the target block weight is 500ms, as opposed to 2s on the Relay Chain, so blocks will be relatively more full for a given number of transactions. Is 1/10 OK or are there arguments for another value?
2. What to do with them?
  a. Burn some portion and give the rest to the collator (or burn 0 and give all to the collator, but I believe this has some economic issues).
  b. Give to a Relay Chain validator and let them handle the validator/treasury split.
  c. Add an account to Statemint over which the Relay Chain Council has control and send fees (or some portion) there.

**Comment by burdges** [comment]
I'd scale fees by how many nodes actually check transactions.  If we've parathreads chunking up nullifier sets for a sharded zcash style thing, or parachains using sassafras, then we might only require 30 checkers total so then if the relay chain has 1500 nodes then we're talking parachain tx costing 1/50th for similar tx.  We might consider relay chain space more valuable for other reasons too, so maybe parachain tx cost even less.

**Comment by burdges** [comment]
We originally preferred mostly burning tx fees, like 80%, but then this got changed for reasons I forget.

**Comment by joepetrowski** [comment]
Will do the following, at least for launch:

- All fees go into a staking pot
- Half the value of the staking pot is paid out to the author in staking's `on_finalize`.

In effect, the author takes 50% of the value of the pot prior to the block and 50% of each tx fee (with the other 50% going into the pot for future authors). Will be implemented in #9 .
