### ISSUE TITLE
Interpret XCM

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/statemint#3]
The parachain should support sending and receiving assets to/from other parachains.

**Comment by riusricardo** [comment]
Tracking issue:
https://github.com/paritytech/polkadot/issues/2841

**Comment by apopiak** [comment]
We'll need to upgrade Polkadot to https://github.com/paritytech/polkadot/pull/2896 and Cumulus to https://github.com/paritytech/cumulus/pull/407

**Comment by mattsse** [comment]
just a question for me to understand: 
sending and receiving assets to/from other parachains, will likely be supported using the `Xcm::WithDraw` and `Xcm::Deposit` variants? That would mean the `AssetTransactor` and `IsReserve` types  of the `XcmConfig` will make use of the `assets` pallet somehow (conversion of `MultiAsset::ConcreteFungible` -> `AssetId`), but are currently only configured to allow the relay chain to withdraw/deposit/teleport ROC  right?

**Comment by joepetrowski** [comment]
Correct, as configured now it teleports ROC between Statemint and the Relay Chain. @riusricardo should know know more about how to send cross-chain asset messages.
