### ISSUE TITLE
Why RelayNetwork is Polkadot?

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/statemint#67]
In this line:

https://github.com/paritytech/statemint/blob/7a5340f54738e7f0379e63dc69ee4d9396009af6/runtime/statemint/src/lib.rs#L443

The RelayNetwork is specified as Polkadot. Shouldn't it be Kusama when launched on Kusama?

**Comment by riusricardo** [comment]
Thanks for the heads up. It needs to be fixed to Kusama.
https://github.com/paritytech/statemint/blob/master/runtime/statemine/src/lib.rs#L442
