### ISSUE TITLE
Support NFTs

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/statemint#7]
The Assets pallet is designed for _fungible_ assets. At some point in the future (probably after initial launch), add logic to support non-fungible assets.

**Comment by joepetrowski** [comment]
Depends on https://github.com/paritytech/substrate/pull/8813

**Comment by apopiak** [comment]
> Depends on [paritytech/substrate#8813](https://github.com/paritytech/substrate/pull/8813)

that's implemented, so I guess we can close

**Comment by apopiak** [comment]
also see https://github.com/paritytech/cumulus/pull/493
