### ISSUE TITLE
Will Statemint be registered in BIP-0044 coin types?

### ISSUE THREAD

**Issue by Lohann** [paritytech/statemint#84]
Should parachains like statemint be registered in [BIP-0044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) coin types?

This question can be applied to any parachain, once non-standalone parachains/parathreads are ephemeral as it can lose an auction and consequently be "kicked" from [polkadot shared security](https://wiki.polkadot.network/docs/en/learn-security). Should parachains like Statemint be registered in BIP-0044? If they don't, how users will store assets in their third-part wallets and do transfers?

Links
- [BIP-44: Multi-Account Hierarchy for Deterministic Wallets ](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)
- [Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

**Comment by joepetrowski** [comment]
I'm not sure what you mean by "parachains like Statemint" or "non-standalone parachains".

Addresses on Statemint should be usable on other parachains in the network, especially as more common good parachains get rolled out, like Staking, Elections, and Governance. One address should be able to have state on multiple chains. Using unique BIP44 paths for each one would result in different key pairs for each one.

I do think that wallets/applications will need to re-evaluate some of their assumptions, as a multi-chain application paradigm will be different to a single chain paradigm. As applications/balances will be spread across multiple chains, it will make sense for addresses to exist in the context of multiple chains.

**Comment by Lohann** [comment]
> I'm not sure what you mean by "parachains like Statemint" or "non-standalone parachains".

@joepetrowski not sure if I'm using the right words, but by standalone chain I mean **Bitcoin**, **Ethereum**, etc, chains that will continue existing and operating independently of polkadot network, however I know they still need a bridge parachain/parathread like [snowbridge](https://snowbridge-docs.snowfork.com/) to continue existing in polkadot network. By non-standalone I mean parachains like statemint that if don't have a reserved slot, stop to operate completely.

> As applications/balances will be spread across multiple chains, it will make sense for addresses to exist in the context of multiple chains.

Currently Polkadot BIP-0044 coin id is `0x80000162` and Kusama is `0x800001b2`, so do you think Statemint addresses will use the same base coin id as polkadot?

> Addresses on Statemint should be usable on other parachains in the network

It maybe a quite challenge too, because if I understand correctly, Polkadot doesn't make any assumption about how a parachain operates, it means that one parachain can implement a [UTxO based model](https://www.youtube.com/watch?v=Q3hjtHaB3rA) to track balances, or even not follow [Polkadot's address format](https://wiki.polkadot.network/docs/en/learn-accounts#address-format).

**Comment by Lohann** [comment]
> I do think that wallets/applications will need to re-evaluate some of their assumptions, as a multi-chain application paradigm will be different to a single chain paradigm

I think this standard must be defined by the Polkadot community, not by wallets and applications, for example [polkadot have its key derivation path documented here](https://wiki.polkadot.network/docs/en/learn-accounts#derivation-paths). But I didn't find any reference to parachain's accounts in this derivation standard, is there any discussion about that going on behind the scenes?

**Comment by Lohann** [comment]
Is not clear for me if statemint mnemonic path derivate from `<mnemonic phrase>//statemint` or is this rule applied only to kusama/polkadot, which are different networks not parachains in the same network

**Comment by burdges** [comment]
We never enforce anything about key derivation on-chain, and soft derivations always bring related key attack worries, so..

We should prevent cross chain related key attacks by using context in the signature, not derivation, maybe good reasons exist for doing cross chain signatures, like airdrops, voting with staked dots on a parachain by providing a merkle proof into relay chain state, etc.  

We've envision an extremely wide range of chains running on polkadot, so really nobody should feel too hemmed in by what others do.  In the short term, I suppose "standards" here serve mostly to help developers avoid thinking about details which they'd consider distracting.

I do however ask that folks proposing standards read about ZCash's unified addresses because they deal specifically with multiple wallets supporting only a subset of valid ZCash transactions. 
- https://github.com/zcash/zips/issues/470
- https://github.com/zcash/zips/issues/478
- https://github.com/zcash/zips/pull/485

**Comment by xlc** [comment]
The genesis hash is part of the signature payload so we don't have replay attack here (unless some parachain choose to not include it).

Requiring different key derivation path is 100% going to cause many UX burdens and make crosschain interaction complicated (e.g. user make tx on chain A to transfer asset on chain B to chain C, now we need a way to somehow proof the ownership on chain B)
