### ISSUE TITLE
Collator staking pallet 

### ISSUE THREAD

**Issue by JesseAbram** [paritytech/statemint#9]
as discussed [here](https://github.com/paritytech/statemint/issues/2#issuecomment-800277543)

A new simple staking pallet for collators needs to be created

**Comment by JesseAbram** [comment]
Although Simple Staking was merged there are a few things still needed to be done

TODO 

- [ ] implement Aura and set new validators 
- [ ] implement simple era 
- [ ] implement last_block booting for missed block authorship

**Comment by kianenigma** [comment]
I'd like to take care of the remaining items tomorrow.

**Comment by kianenigma** [comment]
Yes, updated all PRs is the comment.
