### ISSUE TITLE
How to get bootnodes address?

### ISSUE THREAD

**Issue by 454076513** [paritytech/statemint#94]
Hi, Can you help me. I have built success. but can't find Parachain peer?  please give a address
![image](https://user-images.githubusercontent.com/11207461/120757631-e7b91500-c564-11eb-96d3-e9a06b78de89.png)

**Comment by nuke-web3** [comment]
You can set these in your `chain_spec.rs` or follow the guide here to set explicit nodes to connect to: https://substrate.dev/docs/en/tutorials/start-a-private-network/alicebob
