### ISSUE TITLE
Statemine stop producing block

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/statemint#97]
Hi, statemine seems stop producing block now
![image](https://user-images.githubusercontent.com/14008461/123956649-07761880-d9ff-11eb-92cc-d421dcac9760.png)

**Comment by ddorgan** [comment]
@AlexZhenWang thanks for opening this issue. Blocks are now being produced again, closing.

**Comment by AlexZhenWang** [comment]
Thanks for the quick react @ddorgan !
